{{- if and (ne .Values.dataStore.dbSecret.name "")  (ne .Values.dataStore.sql.password "")  }}
{{- fail "Only one of dataStore.dbSecret.name or dataStore.sql.password should be set" }}
{{- end }}

{{- if ne .Values.dataStore.sql.databaseType "sqlite3" }}
{{- if eq .Values.dataStore.dbSecret.name "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.fullname" . }}-dbpw
  namespace: {{ include "spire-server.namespace" . }}
data:
  DBPW: {{ .Values.dataStore.sql.password | b64enc }}
{{- end }}
{{- end }}
